---
abstract: '15-th competing Postgres connector'
author:
  - 'Author <mmonk@cpan.org>'
build_requires:
  DBI: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  FindBin: '0'
  Test::Deep: '0'
  Test::Harness: '0'
  Test::More: '0'
  Test::PostgreSQL: '0'
  URI: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-PostgreSQL
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '0'
  AnyEvent::Pg: '0'
  AnyEvent::Socket: '0'
  Carp: '0'
  Data::Dumper: '0'
  Mouse: '0'
  Pg::PQ: '0'
  Time::HiRes: '0'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
