%global         _distribution AnyEvent-PostgreSQL
%{?scl:%scl_package package_name}
%{!?scl:%global pkg_name %{_distribution}}

Name:           %{?scl_prefix}perl-%{_distribution}
Version:        0.02
Release:        2%{?dist}
Summary:        Async PostgreSQL connector for perl5 with convient interface
License:        OSI-Approved
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-PostgreSQL/
Source0:        http://www.cpan.org/modules/by-module/AnyEvent/AnyEvent-PostgreSQL-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  %{?scl_prefix}perl(AnyEvent)
BuildRequires:  %{?scl_prefix}perl(AnyEvent::Pg)
BuildRequires:  %{?scl_prefix}perl(DBI)
BuildRequires:  %{?scl_prefix}perl(ExtUtils::MakeMaker)
BuildRequires:  %{?scl_prefix}perl(Mouse)
BuildRequires:  %{?scl_prefix}perl(Pg::PQ)
BuildRequires:  %{?scl_prefix}perl(Test::Deep)
BuildRequires:  %{?scl_prefix}perl(Test::Harness)
BuildRequires:  %{?scl_prefix}perl(Test::More)
BuildRequires:  %{?scl_prefix}perl(Test::PostgreSQL)
BuildRequires:  %{?scl_prefix}perl(Time::HiRes)
BuildRequires:  %{?scl_prefix}perl(URI)
BuildRequires:  postgresql95
BuildRequires:  postgresql95-server
Requires:       %{?scl_prefix}perl(AnyEvent)
Requires:       %{?scl_prefix}perl(AnyEvent::Pg)
Requires:       %{?scl_prefix}perl(Mouse)
Requires:       %{?scl_prefix}perl(Pg::PQ)
Requires:       %{?scl_prefix}perl(Time::HiRes)
Requires:       %{?scl_prefix}perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
%{?scl:Requires: %scl_runtime}

%description
AnyEvent::PostgreSQL - 15-th competing Postgres connector

%prep
%setup -q -n AnyEvent-PostgreSQL-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
POSTGRES_HOME=/usr/pgsql-9.5 make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jul 05 2017 Author 0.01-2
- Adopt spec to build with perl516 software collection
* Wed Jul 05 2017 Author 0.01-1
- Specfile autogenerated by cpanspec 1.78.
